# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: curl -sSL https://get.haskellstack.org/ | sh
  displayName: 'install haskell'
- script: stack setup --allow-different-user
  displayName: 'haskell-setup'
- script: stack install --allow-different-user
  displayName: 'Build Code'
- task: CopyFiles@2
  inputs:
    SourceFolder: '/home/vsts/.local/bin'
    Contents: 'dockerlint'
    TargetFolder: '/home/vsts/work/1/s'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'artifact'
    publishLocation: 'Container'


